# Picked glibc 2.21 to support Ubuntu 14.04+

[target.x86_64-unknown-linux-gnu]
zig = "2.21"
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge" 

[target.aarch64-unknown-linux-gnu]
zig = "2.21"
