-- All main views
---@alias ViewTable table<string, string[]>
---@type ViewTable
return {
  overview = { "overview" },
  ["api-resources"] = { "api-resources", "apiresources" },
  pods = { "pods", "pod", "po" },
  deployments = { "deployments", "deployment", "deploy", "deployments.apps" },
  statefulsets = { "statefulsets", "statefulset", "statefulsets.apps", "sts" },
  replicasets = { "replicasets", "replicaset", "rs", "replicasets.apps" },
  daemonsets = { "daemonsets", "daemonset", "ds", "daemonsets.apps" },
  jobs = { "jobs", "job", "jo", "jobs.batch" },
  cronjobs = { "cronjobs", "cronjob", "cj", "cronjobs.batch" },
  events = { "events", "event", "ev", "events.events.k8s.io" },
  horizontalpodautoscalers = {
    "horizontalpodautoscalers",
    "horizontalpodautoscaler",
    "hpa",
    "horizontalpodautoscalers.autoscaling",
  },
  nodes = { "nodes", "node", "no" },
  namespaces = { "ns", "namespace", "namespaces" },
  serviceaccounts = { "serviceaccounts", "serviceaccount", "sa" },
  secrets = { "secrets", "secret", "sec" },
  storageclasses = { "storageclasses", "storageclass", "sc", "storageclasses.storage.k8s.io" },
  services = { "services", "service", "svc" },
  configmaps = { "configmaps", "configmap", "cm" },
  crds = { "customresourcedefinitions", "crds", "crd", "customresourcedefinitions.apiextensions.k8s.io" },
  contexts = { "contexts", "context" },
  persistentvolumes = { "persistentvolumes", "persistentvolume", "pv" },
  persistentvolumeclaims = { "persistentvolumeclaims", "persistentvolumeclaim", "pvc" },
  clusterroles = { "clusterroles", "clusterrole", "clusterroles.rbac.authorization.k8s.io" },
  clusterrolebindings = {
    "clusterrolebindings",
    "clusterrolebinding",
    "clusterrolebindings.rbac.authorization.k8s.io",
  },
  top = { "top" },
  ingresses = { "ingresses", "ingress", "ing", "ingresses.networking.k8s.io" },
  helm = { "helm" },
}
