--- @class kubectl.DashboardSession
--- @field write fun(self: kubectl.DashboardSession, data: string)
--- @field read_frame fun(self: kubectl.DashboardSession): table?
--- @field resize fun(self: kubectl.DashboardSession, width: number, height: number)
--- @field open fun(self: kubectl.DashboardSession): boolean
--- @field close fun(self: kubectl.DashboardSession)

--- @class kubectl.ClientImplementation
--- @field init_runtime fun(context_name: string)
--- @field init_logging fun(filepath: string)
--- @field init_metrics fun()
--- @field get_resource fun(resource_name: string, group: string?, version: string?, name: string?, namespace: string?)
--- @field get_all fun(gvk: {}, ns: string?)
--- @field get_single fun(gvk: {}, ns: string?, name: string, output: string?)
--- @field start_watcher fun(resource_name: string, group: string?, version: string?, name: string?, namespace: string?)
--- @field edit_resource fun(resource_name: string, namespace: string?, name: string, group: string?, version: string? )
--- @field exec fun(ns: string, pod: string, container: string?, cmd: {})
--- @field debug fun(ns: string, pod: string, image: string, target: string?)
--- @field portforward_start fun(kind: string, name: string, namespace: string, local_port: number, remote_port: number)
--- @field portforward_list fun()
--- @field portforward_stop fun(id: number)
--- @field daemonset_set_images fun(name: string, ns: string, image_spec: {} )
--- @field deployment_set_images fun(name: string, ns: string, image_spec: {} )
--- @field statefulset_set_images fun(name: string, ns: string, image_spec: {} )
--- @field start_dashboard fun(view_name: string)
--- @field start_buffer_dashboard fun(view_name: string): kubectl.DashboardSession
--- @field create_job_from_cronjob fun(j_name: string, ns: string, cj_name: string, dry_run: boolean )
--- @field suspend_cronjob fun(cj_name: string, ns: string, suspend: boolean)
--- @field uncordon_node fun(name: string)
--- @field cordon_node fun(name: string)
--- @field get_config fun()
--- @field setup_queue fun()
--- @field pop_queue fun()
--- @field emit fun(key, payload)
