--- @class kubectl.ClientImplementation
--- @field init_runtime fun(context_name: string)
--- @field init_logging fun(filepath: string)
--- @field get_resource fun(resource_name: string, group: string?, version: string?, name: string?, namespace: string?)
--- @field start_watcher fun(resource_name: string, group: string?, version: string?, name: string?, namespace: string?)
--- @field edit_resource fun(resource_name: string, namespace: string?, name: string, group: string?, version: string? )
--- @field portforward_start fun(kind: string, name: string, namespace: string, local_port: number, remote_port: number)
--- @field portforward_list fun()
--- @field portforward_stop fun(id: number)
